"""Add title for payment table

Revision ID: 9e41ed2f2892
Revises: fc46f64e276b
Create Date: 2025-01-24 21:09:21.178018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e41ed2f2892'
down_revision: Union[str, None] = 'fc46f64e276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'title')
    # ### end Alembic commands ###
