"""Add title to payments

Revision ID: cd5b643a519c
Revises: fc46f64e276b
Create Date: 2025-01-27 17:35:52.199637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd5b643a519c'
down_revision: Union[str, None] = 'fc46f64e276b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'title')
    # ### end Alembic commands ###
