"""Add payment_options table

Revision ID: 0aa2da39e37a
Revises: 9e41ed2f2892
Create Date: 2025-02-02 13:29:07.233164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aa2da39e37a'
down_revision: Union[str, None] = '9e41ed2f2892'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_options',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_options_id'), 'payment_options', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_options_id'), table_name='payment_options')
    op.drop_table('payment_options')
    # ### end Alembic commands ###
