"""Replacement email_name to email and name

Revision ID: 65939cd9f849
Revises: 166d0634dfce
Create Date: 2025-04-17 17:54:41.011617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65939cd9f849'
down_revision: Union[str, None] = '166d0634dfce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('name', sa.String(), nullable=False))
    op.add_column('subscriptions', sa.Column('email', sa.String(), nullable=False))
    op.drop_column('subscriptions', 'email_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('email_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('subscriptions', 'email')
    op.drop_column('subscriptions', 'name')
    # ### end Alembic commands ###
