"""Add notified fields in subscription

Revision ID: df81c06cfafc
Revises: 65939cd9f849
Create Date: 2025-05-11 15:44:17.860416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df81c06cfafc'
down_revision: Union[str, None] = '65939cd9f849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('notified_3_days', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('notified_1_day', sa.Boolean(), nullable=False))
    op.add_column('subscriptions', sa.Column('notified_expired', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriptions', 'notified_expired')
    op.drop_column('subscriptions', 'notified_1_day')
    op.drop_column('subscriptions', 'notified_3_days')
    # ### end Alembic commands ###
